# PgBouncer service for PostgreSQL connection pooling
services:
  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: pgbouncer
    environment:
      - DATABASES_HOST=postgres-splice
      - DATABASES_PORT=5432
      - DATABASES_USER=cnadmin
      - DATABASES_PASSWORD=supersafe
      - DATABASES_DBNAME=dserv
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
    ports:
      - "5432:5432" # PgBouncer proxy
    depends_on:
      - postgres-splice
    restart: always
    networks:
      - default
