services:
  participant:
    environment:
      - CANTON_PARTICIPANT_ADMIN_USER_NAME=ledger-api-user

  validator:
    environment:
      - SPLICE_APP_VALIDATOR_WALLET_USER_NAME=administrator
      - SPLICE_APP_VALIDATOR_LEDGER_API_AUTH_USER_NAME=ledger-api-user

  wallet-web-ui:
    environment:
      - SPLICE_APP_UI_UNSAFE=true
      - SPLICE_APP_UI_UNSAFE_SECRET=unsafe

  ans-web-ui:
    environment:
      - SPLICE_APP_UI_UNSAFE=true
      - SPLICE_APP_UI_UNSAFE_SECRET=unsafe
